CREATE TABLE BOOK( 
    DOCID int(11) NOT NULL, 
    ISBN int(11) NOT NULL, 
    PRIMARY KEY(DOCID), 
    CONSTRAINT DOCBOOK 
    FOREIGN KEY(DOCID) REFERENCES DOCUMENT(DOCID) 
    ON DELETE CASCADE ON UPDATE CASCADE 
);
