CREATE TABLE IF NOT EXISTS `DOCUMENT` (
      `DOCID` int(11) NOT NULL,
      `TITLE` varchar(50) NOT NULL,
      `PDATE` date NOT NULL,
      `PUBLISHERID` int(11) DEFAULT NULL,
      PRIMARY KEY (`DOCID`),
      KEY `PUBLISHERID`(`PUBISHERID`);
      CONSTRAINT `DOCPUB` FOREIGN KEY (`PUBLISHERID`) REFERENCES `PUBLISHER` (`PUBLISHERID`) 
      ON DELETE SET NULL ON UPDATE CASCADE
);
